stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cargo build

lib-test-job:
  stage: test
  script:
    - cargo test --tests

doc-test-job:
  stage: test
  script:
    - cargo test --doc

lint-test-job:
  stage: test
  script:
    - cargo clippy

deploy-job:
  stage: deploy
  script:
    - cargo publish
