stages:
  - build
  - test
  - lint

build:
  stage: build
  script:
    - cargo build --target-dir /home/kyran/.cache/build-output/

test:
  stage: test
  script:
    - cargo test --tests --target-dir /home/kyran/.cache/build-output/

doc-test:
  stage: test
  script:
    - cargo test --doc --target-dir /home/kyran/.cache/build-output/

check-clippy:
  stage: lint
  script:
    - cargo clippy
  allow_failure: true

check-fmt:
  stage: lint
  script:
    - cargo fmt --check
  allow_failure: true
