[book]
authors = ["Taehoon Moon <taehoon.moon@outlook.com>", "Kyran Gostelow <kyran@gostelow.me>"]
title = "MultiSQL Documentation - OUT OF DATE"
license = "Apache-2.0"
language = "en"
multilingual = false
